### PR TITLE
New text alignment modes

### PR DESCRIPTION
**Pull request by oomek**
Added the following:
Align.TopLeft, Align.TopRight, Align.TopCentre,
Align.BottomLeft, Align.BottomRight, Align.BottomCentre,
Align.MiddleLeft, Align.MiddleRight, Align.MiddleCentre

Removed trailing spaces for aligned text, so it sticks to the edges evenly.

The old , Align.Left, Align.Right, Align.Centre are still working with the old method for compatibility.

See the following forum post for details and screensots:
http://forum.attractmode.org/index.php?topic=2292.0

### CODE REVIEW

**Comment by oomek** [comment]
In case you are wondering if it breaks the old alignment modes I'd like to assure you that it doesn't.
I did 2 screensots of each layout before and after my commits, then I compared them in photoshop. It all aligns perfectly, so it's safe to merge.

**Comment by oomek** [comment]
I’m about to rewrite the fit_string() and setString() functions now which seem to me a little over complicated after my modifications, so please hold any further analysis.

**Comment by oomek** [comment]
I have identified a cpu hog and a memory leak when you use fe.Text with default font as a rectangle filled with colour. Some devs do this in layouts. This causes generating huge glyphs and tanks the cpu and memory. I’m working on a fix to prevent unnecessary calls to getGlyph() and setScale()

**Comment by oomek** [comment]
Still trying to figure out a better way of positioning the cursor so the text do not jiggle while scrolling the cursor, so do not be surprised that it isn’t there.

**Comment by oomek** [comment]
I think I'm done with this PR.
I've reimplemented an original text cursor behaviour for now and added/fixed a few more things.
I hope you like the animated vertical cursor.

**Comment by mickelson** [comment]
Hi I just started playing around with this pull request. It's looking pretty good to me, but I have determined that this PR breaks the up and down scrolling of the History.dat plugin.  It looks like the (undocumented) Text.first_line_hint attribute that is exposed in squirrel is broken somehow by your changes.  The History.dat plugin sets changes the first_line_hint attribute to scroll the text up and down where the information it is showing is too big to fit on screen all at once.

**Comment by oomek** [comment]
I will look into it, thanks for letting me know. Oh and btw, yesterday I added one more missing but crucial property. line_spacing factor

**Comment by oomek** [comment]
I've fixed scrolling in history.dat and added a new properety for Text "line_spacing"
Would you test it please and let me know in case something else is still broken.

**Comment by oomek** [comment]
Do you think it would be a good idea to rename the charsize to char_size and nomargin to margin( default true) ?
So we have consistency across properties like so:
char_size
glyph_size
char_spacing
line_spacing
margin

The properties charsize and nomargin would be preserved for compatibility

**Comment by mickelson** [comment]
sure sounds good to me 👍

**Comment by oomek** [comment]
Done.
I've decided to modify the behaviour of margin property. it's now an int instead of a bool. We can now precisely set the margin in pixels. Default value is -1 which is the old value calculated from the char size. 0 acts as the old nomargin property. I hope you see what I'm aiming for, a pixel perfect positioning of text, so no more guess work.

**Comment by oomek** [comment]
Here is my layout for testing the align modes margins and line spacing:
```
local flw = fe.layout.width
local flh = fe.layout.height

local char_size = 20
local word_wrap = true	

//local FONT_FILE = "Swiss721BT-BoldCondensed.otf"
//local FONT_FILE = "BebasNeueRegular.otf"
//local FONT_FILE = "BarlowCondensed-Regular2.ttf"
//local FONT_FILE = "Asimov.otf"
//local FONT_FILE = "Aquilone-Regular.otf"

local LOREM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam id nisi id libero hendrerit eleifend. Sed tincidunt vitae neque maximus imperdiet."

local bg = fe.add_text( "", 0, 0, flw, flh )
bg.set_bg_rgb( 100, 100, 200 )

local legend_margin = fe.add_text( "margin: 0", 0, 0, 200, 24 )
local legend_spacing = fe.add_text( "spacing: 1", 0, 30, 200, 24 )
local legend_keys = fe.add_text( "up: height -\ndown: height +\nleft: width -\nright: width +\nnext_page: margin +\nprev_page: margin -\nnext_letter: line spacing +\nprev_letter: line spacing -", 0, 100, 300, 300 )
legend_margin.align = Align.TopLeft
legend_spacing.align = Align.TopLeft
legend_keys.align = Align.TopLeft
legend_keys.char_size = 20
legend_keys.word_wrap = true

local t = []
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 1.0 ), floor( flh / 7.0 * 1.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 3.0 ), floor( flh / 7.0 * 1.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 5.0 ), floor( flh / 7.0 * 1.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 1.0 ), floor( flh / 7.0 * 3.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 3.0 ), floor( flh / 7.0 * 3.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 5.0 ), floor( flh / 7.0 * 3.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 1.0 ), floor( flh / 7.0 * 5.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 3.0 ), floor( flh / 7.0 * 5.0), floor( flw / 4.0), floor( flh / 8.0 )) )
t.push( fe.add_text( LOREM, floor( flw / 7.0 * 5.0 ), floor( flh / 7.0 * 5.0), floor( flw / 4.0), floor( flh / 8.0 )) )

t[0].align = Align.TopLeft
t[1].align = Align.TopCentre
t[2].align = Align.TopRight
t[3].align = Align.MiddleLeft
t[4].align = Align.MiddleCentre
t[5].align = Align.MiddleRight
t[6].align = Align.BottomLeft
t[7].align = Align.BottomCentre
t[8].align = Align.BottomRight

foreach ( o in t )
{
	o.charsize = char_size
	o.set_bg_rgb( 0, 0, 0 )
	o.bg_alpha =  100
	o.margin = 0
	o.word_wrap = word_wrap
	try {o.font = FONT_FILE} catch( e ) {}
}

local block = true
local update = false

function signal(sig)
{
	update = true
	switch ( sig )
	{
		case "up":
			foreach ( o in t ) ( o.height <= 0 ) ? 1 : o.height--
			return block
		case "down":
			foreach ( o in t ) o.height += 1
			return block
		case "left":
			foreach ( o in t ) ( o.width <= 0 ) ? 1 : o.width--
			return block
		case "right":
			foreach ( o in t ) o.width++
			return block
		case "prev_page":
			foreach ( o in t ) o.margin--
			return block
		case "next_page":
			foreach ( o in t ) o.margin++
			return block
		case "prev_letter":
			foreach ( o in t ) o.line_spacing -= 0.1
			return block
		case "next_letter":
			foreach ( o in t ) o.line_spacing += 0.1
			return block
	}
}
fe.add_signal_handler( "signal" )

function tick( ttime )
{
	if ( update == true )
	{
		legend_margin.msg = "margin: " + t[0].margin
		legend_spacing.msg = "spacing: " + t[0].line_spacing
		update = false
	}
}
fe.add_ticks_callback( "tick" )
```

**Pull request merged**
