### PR TITLE
Fixed high CPU on video playback and video freezing on wake

### PR DESCRIPTION
**Pull request by oomek**
Some snap videos ( ie. Proggetto Snaps ) consumed excessive amount of CPU. This was caused by  max_sleep being dependent on the time base instead of the frame rate.
Fixed video freezing after resuming from sleep, which was caused by only showing key frames.  Videos now restart when computer wakes up.

### CODE REVIEW

**Comment by mickelson** [comment]
I understand the fix for excessive CPU usage due to how max_sleep is set, good catch there.

I'm not following the other change mixed in with the pull request though.  (this is where having separate PRs for each fix helps).  It appears that you are trying to stop the video from only showing key frames after resuming from a sleep.

The displaying of just key frames is currently controlled by us with the qscore variable and the set_avdiscard_from_qscore() function.  I wonder if a simpler fix for the second issue would be to simply keep the qscore at a higher value when you detect that the computer is recovering from a sleep??

**Comment by oomek** [comment]
Yes, max sleep for some videos was less than millisecond. I've tried reserting qscore, but it did not have any effect for some reason. Having videos restart after reauming from sleep and not stutter seemed a logical solution for me.

**Comment by oomek** [comment]
Regarding the separate PRs. This is a bit troublesome when I edit the same files in separate commits. Nobody likes conflicts I believe.

**Comment by oomek** [comment]
So, are you ok to merge this PR? This bug was haunting me for a long time, I'm glad I finally found the source of those crashes. The logs from FeVideo are still sometimes mangled with the main thread though. A simple mutex is not going to work without refactoring the log functions as you have used references for the log targets, but that's a minor issue to be fixed in the future.

**Comment by mickelson** [comment]
Sorry this PR is fixing crashes?  Or do you mean the nowide PR?

**Comment by oomek** [comment]
Sorry, this comment indeed does not belong here. I should stop answering on the mobile phone.

**Comment by mickelson** [comment]
yup I'm going to merge it now

**Pull request merged**
