### PR TITLE
Adding mmal support for Pi 4

### PR DESCRIPTION
**Pull request by chase-cobb**
This commit adds support for mmal on Pi 4 by creating a new preprocessor define and passing it through the makefile. Tested on Pi 4 in Raspian Buster.

### CODE REVIEW

**Comment by tonberryhunter** [comment]
Thank you

**Comment by chase-cobb** [comment]
@mickelson Is the CI server down? It looks like its not running.

**Comment by chase-cobb** [comment]
Anyone interested in this PR should also be mindful of [this ticket.](https://github.com/mickelson/attract/issues/236)

**Comment by mickelson** [comment]
Not sure what is going on with the CI, but I'll go ahead and merge this now.
Thanks!

**Pull request merged**
