### PR TITLE
Re implemented refresh rate detection

### PR DESCRIPTION
**Pull request by oomek**
Refresh rate is now detected with routines specific to each platform.

### CODE REVIEW

**Review by keilmillerjr — APPROVED** [review]
Tested with Mac and Linux. Able to obtain refresh rate on both platforms.

**Comment by oomek** [comment]
Thanks @keilmillerjr for your tests. @mickelson are we ready to merge it?

**Comment by mickelson** [comment]
The addition of the xrandr dependency in attract is causing the linux compiles for this to fail on travis-ci... i think you should update the Compile.md file as part of this PR to instruct people compiling on linux (X11) that they will need to also install the xrandr-dev library now to successfully compile.  xrandr is an SFML dependency but the user won't necessarily have the dev package for it installed.  You should also update the .travis.yml file to add the libxrandr-dev package so the continuous integration will still work after PR.


Here is the compile message:

```
$ make -j8

flags: -Wl,--export-dynamic -I/usr/include/freetype2   -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -D__STDC_CONSTANT_MACROS -I/usr/include/freetype2  -I/usr/include/x86_64-linux-gnu -I/usr/include/AL   -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/nowide -Iextlibs/nvapi -Iextlibs/rapidjson/include -Iextlibs/gameswf  -DUSE_XLIB -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_LIBARCHIVE -DUSE_LIBCURL -DUSE_SWRESAMPLE

mkdir -p obj

mkdir -p obj/squirrel

mkdir -p obj/sqstdlib

mkdir -p obj/gsbaselib

mkdir -p obj/gameswflib

mkdir -p obj/audiolib

mkdir -p obj/gameswflib/gameswf_as_classes

Compiling obj/fe_base.o...

Compiling obj/fe_file.o...

Compiling obj/fe_info.o...

Compiling obj/fe_romlist.o...

Compiling obj/fe_util_sq.o...

Compiling obj/fe_util.o...

Compiling obj/fe_input.o...

Compiling obj/fe_cmdline.o...

In file included from /usr/include/c++/5/backward/hash_map:60:0,

                 from extlibs/gameswf/base/container.h:75,

                 from extlibs/gameswf/base/image.h:14,

                 from extlibs/gameswf/gameswf/gameswf.h:21,

                 from src/fe_base.cpp:34:

/usr/include/c++/5/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]

 #warning \

  ^

Compiling obj/fe_settings.o...

Compiling obj/scraper_base.o...

Compiling obj/scraper_xml.o...

Compiling obj/scraper_general.o...

Compiling obj/scraper_net.o...

Compiling obj/scraper_gamesdb.o...

Compiling obj/fe_config.o...

Compiling obj/fe_presentable.o...

Compiling obj/fe_present.o...

Compiling obj/sprite.o...

src/fe_present.cpp:42:35: fatal error: X11/extensions/Xrandr.h: No such file or directory

compilation terminated.

Makefile:485: recipe for target 'obj/fe_present.o' failed

make: *** [obj/fe_present.o] Error 1

make: *** Waiting for unfinished jobs....

The command "make -j8" exited with 2.
```

[https://travis-ci.org/github/mickelson/attract/jobs/730332044](url)

**Comment by oomek** [comment]
Yes, I was unsure about that dependency whether it's a part of X11 or not. Thanks for confirming.

**Comment by oomek** [comment]
How do I restart travis job? I seem not to have access to it anymore.

**Pull request merged**
