### PR TITLE
Added Overlay.Favourite command to Transition.ShowOverlay

### PR DESCRIPTION
**Pull request by oomek**

### CODE REVIEW

**Comment by oomek** [comment]
Possible fix in https://github.com/mickelson/attract/pull/484, waiting for review

**Comment by oomek** [comment]
It looks like we are short on reviewers :)

**Comment by mickelson** [comment]
just curious, are you able to review and approve your own pull request?  you should have the access.

**Comment by oomek** [comment]
I cannot approve my own commits.

**Pull request merged**
