### PR TITLE
make make more flexible

### PR DESCRIPTION
**Pull request by h0tw1r3**
With these changes I am able to target darwin and link against SFML 2.3.1 / 2.3.2 (upcoming) from a Linux host.

### CODE REVIEW

**Comment by mickelson** [comment]
hey there, trying this out on my Debian linux setup and make no longer works.

It looks to be choking on the 'lastword' part you've added... I'm not familiar with that.

Errors look like this:

E -c -o obj/fe_base.o src/fe_base.cpp  -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/miniz  -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_AVRESAMPLE -DNO_SWF
E -c -o obj/fe_util.o src/fe_util.cpp  -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/miniz  -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_AVRESAMPLE -DNO_SWF
make: E: Command not found
E -c -o obj/fe_util_sq.o src/fe_util_sq.cpp  -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/miniz  -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_AVRESAMPLE -DNO_SWF
make: E: Command not found
Makefile:322: recipe for target 'obj/fe_base.o' failed
make: [obj/fe_base.o] Error 127 (ignored)
Makefile:322: recipe for target 'obj/fe_util.o' failed
make: [obj/fe_util.o] Error 127 (ignored)
E -c -o obj/fe_info.o src/fe_info.cpp  -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/miniz  -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_AVRESAMPLE -DNO_SWF
make: E: Command not found
E -c -o obj/fe_input.o src/fe_input.cpp  -DDATA_PATH=\"/usr/local/share/attract/\" -O2 -DNDEBUG -Iextlibs/audio/include -I/usr/include/freetype2 -I/usr/include/AL  -Iextlibs/squirrel/include -Iextlibs/sqrat/include -Iextlibs/miniz  -DUSE_XINERAMA -DUSE_FONTCONFIG -DUSE_AVRESAMPLE -DNO_SWF
make: E: Command not found
Makefile:322: recipe for target 'obj/fe_util_sq.o' failed
make: [obj/fe_util_sq.o] Error 127 (ignored)
Makefile:322: recipe for target 'obj/fe_info.o' failed

**Comment by h0tw1r3** [comment]
odd, [I use it all the time](https://www.gnu.org/software/make/manual/html_node/Special-Variables.html). Will try on debian, ubuntu and fedora tomorrow.

**Comment by mickelson** [comment]
ok, so it does work for me if I specifically define CC and CPP at the command line:

make -j 3 CC=gcc CPP=g++

**Comment by h0tw1r3** [comment]
Refactoring. I noticed something else, shouldn't CPP be CXX? Make pre-defines CPP as a preprocessor, and CXX as a compiler.

**Comment by h0tw1r3** [comment]
Should be fixed now.

**Comment by h0tw1r3** [comment]
Tested on host builds on Fedora, Ubuntu 14.04LTS, OSX 10.8, and cross builds for OSX and Windows.
Added EXTRA_CFLAGS for building fat binaries and such (-arch i386 -arch x86_64).

**Comment by mickelson** [comment]
Ok looks great, I've merged this now. Thanks

**Pull request merged**
