### PR TITLE
Feature: mipmaps parameter for fe.Image class

### PR DESCRIPTION
**Pull request by oomek**
Added .mipmaps parameter that gets/sets the automatic generation of mipmaps for the fe.Image objects.

### CODE REVIEW

**Comment by oomek** [comment]
Andrew, would you be able to pull my commits and up an AM version when I finish my 3 features I’m working on? Those features are: Mipmaps, font spacing and blending modes.

**Comment by mickelson** [comment]
sure thing.  when i get some time i’m going to look at implementing “per display” layout parameters.  Hopefully it’s not too difficult.  That bundled with your changed seems like a good place for doing a new version

**Comment by oomek** [comment]
I’m refining my other commit Blending modes which I haven’t pushed yet and I’ve decided to bind it per shader not per drawable and I’ve also changed the default blending mode for surfaces to Premultiplied to fix the black fringes when thre are transparent objects on it. Are you ok with that?

**Comment by oomek** [comment]
What is the purpose of that per display parameter you mentioned.

**Comment by oomek** [comment]
Will open a new pull request after rebasing.

**Pull request closed without merging**
