### PR TITLE
Gathering artwork optimization

### PR DESCRIPTION
**Pull request by oomek**
Replaced directory crawler with checking if a file exists with known extension type. This method is 10x-20x faster (1-2ms instead of 20ms) when tested on the RPI with a library of 5000 pngs.

### CODE REVIEW

**Comment by oomek** [comment]
What about this one? It's in dormant state for quite a while now.

**Comment by mickelson** [comment]
I haven't merged this one (or tested it) yet because it appears to break the documented behaviour of the frontend.

The Readme.md file says Attract-Mode supports any video format supported by FFmpeg.  It was an intentional design decision to automatically work with anything FFmpeg supports.  This change appears to undo that by hardcoding the frontend to only supporting certain specific video extensions.

I suspect this will also break things like animated gif and animated png support, as well as the (undocumented but at one point working) ability to have mp3s or other music files as sound "artworks" that play for particular games, etc.

**Comment by oomek** [comment]
Fair point, but I still think it's worth reconsidering as the gain is significant. If you have any thoughts about improving it let me know.

**Comment by mickelson** [comment]
Hi I took a look and came up with this: c74fd5f8efe03610f8f89bbccbd3e2e0644cbe69
it seems to achieve the speed up without the potential functionality hit

**Comment by oomek** [comment]
Cool, I'm gonna take a look

**Comment by oomek** [comment]
I can see it as an improvement, but would it be really comparable to directly accessing the predetermined filenames?

Correct me if I'm wrong.

Assuming you have a library of 5000 pngs, each path in the array is, let's say 256 bytes long and you have 20 snaps on the screen.

5000x256x20 = around 25MB of data to crawl through on each transition.

**Comment by mickelson** [comment]
The array is sorted and does an optimized search (maybe a binary search depending on stl implementation), so it isn’t touching every element each time.

**Comment by oomek** [comment]
What if we used a map that contains a vector of paths with filenames with found extensions for a certain basename and instead of iterationg through vector we did a lookup using a basename key? Would that be faster that iterating throught the whole vector?

**Comment by oomek** [comment]
Or maybe I'm being paranoid. I just don't have the RPI set up at the moment to benchmark it.

**Comment by oomek** [comment]
This is actually pretty clever what you did. `lower_bound` is actually quite fast on sorted vectors and you stop iterating when the next element does not contain the basename? If so I'm pretty happy with that implementation.

**Pull request closed without merging**
