### PR TITLE
Cleanup version handling and typo

### PR DESCRIPTION
**Pull request by h0tw1r3**

### CODE REVIEW

**Comment by mickelson** [comment]
It occurs to me now that the git processing in the makefile will break the build for people who simply download the source tarball and that aren't building in a git repo.  This needs to get fixed!

The easiest approach, which I don't mind, is to simply define the version number somewhere in the source.  How and where this is done can be rearranged to whatever works for the windows rc file.

**Comment by h0tw1r3** [comment]
> The easiest approach, which I don't mind, is to simply define the version number somewhere in the source. How and where this is done can be rearranged to whatever works for the windows rc file.

With this patch, all you need to do is set the version in the makefile (see FE_VERSION) using the same format you current use for the tag (ie. v1.6.2, v2.0.0-rc1, etc).

If the builder is using the git checkout, it will automatically use the closest HEAD tag to build the version number + the count of commits since last tag + "dirty" if local changes have not been commited. Falls back to parsing (without errors or warning messages) to FE_VERSION.

**Comment by mickelson** [comment]
ok, sounds good.  thanks for the explanation, I'll mrge now

**Comment by h0tw1r3** [comment]
@mickelson Testing a fix for tarball version. Currently it's appending "dirty".

**Pull request merged**
