### PR TITLE
debian-package: fix Build-Depends, fix install Depends, fix Makefile for DESTDIR

### PR DESCRIPTION
**Pull request by philenotfound**
verified in a clean chroot build environment

### CODE REVIEW

**Comment by mickelson** [comment]
Yes, someone who understands debian packaging!  I've been thrashing about with this for a bit now here so any help is much appreciated.

There are a couple of other packages that aren't absolutely necessary but which get used if they are detected at build time.... I'm thinking libavresample-dev, libarchive-dev and libfontconfig1-dev

Could you able to add these to this pull request as well?  thanks!

**Comment by philenotfound** [comment]
Do mean like attract-minimal and attract-full packages?
Or just add the optional ones and build the package with all options enabled?

**Comment by mickelson** [comment]
I mean the latter, add the optional ones and build with all enabled.

The only ones that are truly "optional" imo are xinerama and libarchive,  the others are needed for the frontend to function properly.  I'm not sure if there is a way to simply flag these optional ones as such in the debian package

**Comment by philenotfound** [comment]
Okay, I'll add these too.. I haven't even tested installing the package yet, the PR was just for getting it to compile :-)

**Comment by philenotfound** [comment]
I have rebased on your latest master for the Build-Depends fix.
I have updated the Depends for installing the package on Debian Jessie.
The Makefile required a small fix to correctly install with a DESTDIR.

**Comment by mickelson** [comment]
thank you!

**Pull request merged**
